import { expect, test, type APIRequestContext, type Page } from '@playwright/test'
import { registerAndLogin } from './support/auth'

async function command(request: APIRequestContext, path: string, data?: unknown, method = 'POST') {
  const csrf = await (await request.get('/api/auth/csrf')).json()
  return request.fetch(path, { method, data, headers: { [csrf.headerName]: csrf.token } })
}
async function openWithdrawal(page: Page) {
  await page.goto('/settings?section=account')
  await page.getByRole('button', { name: '회원 탈퇴', exact: true }).click()
  return page.getByRole('dialog')
}

test('B settings preserves menu and draft across resize and lets a no-ledger account withdraw @pr', async ({ page, request }) => {
  const user = await registerAndLogin(page, request, '설정 검증')
  await page.getByRole('link', { name: '내 계정 설정', exact: true }).click()
  await page.getByRole('button', { name: '화면', exact: true }).click()
  await page.getByRole('radiogroup', { name: '화면 모드' }).locator('label').filter({ hasText: '다크' }).click()
  await expect(page.locator('html')).toHaveClass(/dark/)
  await page.getByRole('button', { name: '내 계정', exact: true }).click()
  const dialog = await openWithdrawal(page)
  await dialog.getByLabel('현재 비밀번호').fill('wrong-password')
  await page.setViewportSize({ width: 320, height: 700 })
  await expect(dialog.getByLabel('현재 비밀번호')).toHaveValue('wrong-password')
  await expect(page.locator('body')).toHaveJSProperty('scrollWidth', 320)
  await dialog.getByRole('checkbox').check()
  await dialog.getByRole('button', { name: '회원 탈퇴', exact: true }).click()
  await expect(dialog.getByRole('alert')).toContainText('비밀번호가 일치하지')
  await dialog.getByLabel('현재 비밀번호').fill(user.password)
  await dialog.getByRole('button', { name: '회원 탈퇴', exact: true }).click()
  await expect(page.getByRole('status').filter({ hasText: '회원 탈퇴가 완료' })).toBeVisible()
  await expect(page).toHaveURL(/login\?withdrawn=1$/)
  const login = await command(page.request, '/api/auth/session', { loginId: user.loginId, password: user.password })
  expect(login.status()).toBe(401)
})

test('stale solo withdrawal preserves account until new ledger state is confirmed @pr', async ({ page, request }) => {
  const user = await registerAndLogin(page, request, '마지막 구성원')
  expect((await command(page.request, '/api/ledger-books')).ok()).toBeTruthy()
  const dialog = await openWithdrawal(page)
  await expect(dialog).toContainText('혼자 쓰는 가계부도 함께 삭제')
  expect((await command(page.request, '/api/ledger-books/current/invitations')).ok()).toBeTruthy()
  await dialog.getByLabel('현재 비밀번호').fill(user.password)
  await dialog.getByRole('checkbox').check()
  await dialog.getByRole('button', { name: '탈퇴하고 가계부 삭제' }).click()
  await expect(dialog.getByRole('alert')).toContainText('가계부 구성이 바뀌었어요')
  await dialog.getByRole('button', { name: '최신 내용 다시 확인' }).click()
  await expect(dialog.getByRole('checkbox')).not.toBeChecked()
  await expect(dialog.getByLabel('현재 비밀번호')).toHaveValue(user.password)
  await dialog.getByRole('checkbox').check()
  await dialog.getByRole('button', { name: '탈퇴하고 가계부 삭제' }).click()
  await expect(page.getByRole('status').filter({ hasText: '회원 탈퇴가 완료' })).toBeVisible()
})

test('shared withdrawal preserves partner access and revokes another device session @pr', async ({ page, request, browser }) => {
  const first = await registerAndLogin(page, request, '첫 구성원')
  expect((await command(page.request, '/api/ledger-books')).ok()).toBeTruthy()
  const invitation = await (await command(page.request, '/api/ledger-books/current/invitations')).json()
  const partnerContext = await browser.newContext({ baseURL: test.info().project.use.baseURL ?? process.env.BASE_URL ?? 'http://127.0.0.1:5173' })
  const otherDevice = await browser.newContext({ baseURL: process.env.BASE_URL ?? 'http://127.0.0.1:5173' })
  try {
    const partner = await partnerContext.newPage()
    const second = await registerAndLogin(partner, request, '남은 구성원')
    expect((await command(partner.request, '/api/ledger-invitations/redemptions', { code: invitation.code })).ok()).toBeTruthy()
    expect((await command(otherDevice.request, '/api/auth/session', { loginId: first.loginId, password: first.password })).ok()).toBeTruthy()
    const otherPage = await otherDevice.newPage()
    await otherPage.goto('/settings?section=account')
    await expect(otherPage.getByText(first.email, { exact: true })).toBeVisible()
    const dialog = await openWithdrawal(page)
    await expect(dialog).toContainText('함께 쓴 가계부는 남아요')
    await dialog.getByLabel('현재 비밀번호').fill(first.password)
    await dialog.getByRole('checkbox').check()
    await dialog.getByRole('button', { name: '회원 탈퇴', exact: true }).click()
    await expect(page).toHaveURL(/login\?withdrawn=1$/)
    expect((await otherDevice.request.get('/api/auth/me')).status()).toBe(401)
    expect((await otherDevice.request.get('/api/assets')).status()).toBe(401)
    await otherPage.getByRole('link', { name: '자산', exact: true }).click()
    await expect(otherPage).toHaveURL(/\/login(?:\?|$)/)
    await expect(otherPage.getByText(first.email, { exact: true })).toHaveCount(0)
    const current = await (await partner.request.get('/api/ledger-books/current')).json()
    expect(current.ledger.members.filter((m: { withdrawn: boolean }) => m.withdrawn)).toHaveLength(1)
    expect(current.ledger.members.find((m: { withdrawn: boolean }) => m.withdrawn).displayName).toBe('탈퇴한 구성원')
    await partner.goto('/settings')
    await expect(partner.getByText('구성원 1명')).toBeVisible()
    const last = await openWithdrawal(partner)
    await expect(last).toContainText('혼자 쓰는 가계부도 함께 삭제')
    await last.getByLabel('현재 비밀번호').fill(second.password)
    await last.getByRole('checkbox').check()
    await last.getByRole('button', { name: '탈퇴하고 가계부 삭제' }).click()
    await expect(partner).toHaveURL(/login\?withdrawn=1$/)
  } finally { await partnerContext.close(); await otherDevice.close() }
})
