import { expect, test } from '@playwright/test'
import { randomUUID } from 'node:crypto'

test('signup consent starts unchecked, preserves draft while reading, and is enforced by HTTP @pr', async ({ page }) => {
  await page.goto('/sign-up')
  const loginId = `consent_${randomUUID().replaceAll('-', '').slice(0, 16)}`
  await page.getByLabel('이름', { exact: true }).fill('동의 검증')
  await page.getByLabel('이메일', { exact: true }).fill(`${loginId}@example.test`)
  await page.getByRole('button', { name: '다음', exact: true }).click()
  await page.getByLabel('아이디', { exact: true }).fill(loginId)
  await page.getByRole('button', { name: '중복 확인', exact: true }).click()
  await expect(page.getByRole('button', { name: '확인 완료' })).toBeVisible()
  await page.getByLabel('비밀번호', { exact: true }).fill('Consent-test-2026!')
  await page.getByLabel('비밀번호 확인').fill('Consent-test-2026!')
  await page.getByRole('button', { name: '다음', exact: true }).click()
  const age = page.getByRole('checkbox', { name: '[필수] 만 14세 이상입니다', exact: true })
  const terms = page.getByRole('checkbox', { name: '[필수] 이용약관 동의', exact: true })
  const privacy = page.getByRole('checkbox', { name: '[필수] 개인정보 수집·이용 동의', exact: true })
  await expect(age).not.toBeChecked()
  await expect(terms).not.toBeChecked()
  await expect(privacy).not.toBeChecked()
  await page.getByRole('button', { name: '이용약관 내용 보기' }).click()
  await expect(page.getByRole('dialog')).toContainText('공동 가계부')
  await page.keyboard.press('Escape')
  await expect(page.getByLabel('아이디', { exact: true })).toHaveValue(loginId)
  await expect(terms).not.toBeChecked()
  await page.getByRole('button', { name: '가입하고 인증 메일 받기' }).click()
  await expect(page.getByRole('alert')).toContainText('필수 동의를 완료')
  const csrf = await (await page.request.get('/api/auth/csrf')).json()
  const documents = await (await page.request.get('/api/legal')).json()
  const account = { loginId, displayName: '동의 검증', email: `${loginId}@example.test`, password: 'Consent-test-2026!' }
  const headers = { [csrf.headerName]: csrf.token }
  const missing = await page.request.post('/api/auth/sign-up', { data: account, headers })
  expect(missing.status()).toBe(400)
  expect((await missing.json()).errorCode).toBe('SIGNUP_CONSENT_REQUIRED')
  const old = await page.request.post('/api/auth/sign-up', { data: { ...account, consent: { version: 'old', age14OrOlder: true, termsAccepted: true, privacyAccepted: true } }, headers })
  expect(old.status()).toBe(409)
  expect((await old.json()).errorCode).toBe('SIGNUP_CONSENT_VERSION_CHANGED')
  expect(documents.version).toBeTruthy()
  await age.check(); await terms.check(); await privacy.check()
  await page.setViewportSize({ width: 768, height: 1024 })
  await expect(age).toBeChecked()
  await expect(terms).toBeChecked()
  await expect(privacy).toBeChecked()
  await page.getByRole('button', { name: '가입하고 인증 메일 받기' }).click()
  await expect(page.getByRole('heading', { name: '이메일을 확인해 주세요' })).toBeVisible()
  await page.goto('/legal/privacy')
  await expect(page.getByRole('heading', { name: '개인정보 처리방침' })).toBeVisible()
  await expect(page.getByText('돈독 개인정보 처리방침', { exact: true })).toBeVisible()
})
