-- Dondok initial PostgreSQL schema.
-- UUIDv7 identifiers are generated by the application.
-- Money is stored as whole Korean won in bigint columns.

create table app_user (
    id                        uuid primary key,
    display_name              varchar(100) not null,
    email                     varchar(320) not null,
    email_normalized          varchar(320)
                              generated always as (lower(btrim(email))) stored,
    status                    varchar(30) not null default 'PENDING_VERIFICATION',
    email_verified_at         timestamptz,
    locale                    varchar(10) not null default 'ko-KR',
    time_zone                 varchar(50) not null default 'Asia/Seoul',
    created_at                timestamptz not null default now(),
    updated_at                timestamptz not null default now(),
    withdrawn_at              timestamptz,
    version                   bigint not null default 0,

    constraint uq_app_user_email
        unique (email_normalized),
    constraint ck_app_user_display_name
        check (btrim(display_name) <> ''),
    constraint ck_app_user_email
        check (btrim(email) <> '' and email !~ '[[:space:]]'),
    constraint ck_app_user_status
        check (status in ('PENDING_VERIFICATION', 'ACTIVE', 'LOCKED', 'WITHDRAWN')),
    constraint ck_app_user_email_verified
        check (
            (status = 'PENDING_VERIFICATION' and email_verified_at is null)
            or
            (status <> 'PENDING_VERIFICATION' and email_verified_at is not null)
        ),
    constraint ck_app_user_withdrawn_at
        check ((status = 'WITHDRAWN') = (withdrawn_at is not null))
);

create table local_credential (
    user_id                  uuid primary key
                             references app_user(id) on delete cascade,
    login_id                 varchar(30) not null,
    login_id_normalized      varchar(30)
                             generated always as (lower(login_id)) stored,
    password_hash            varchar(255) not null,
    password_algorithm       varchar(30) not null default 'ARGON2ID',
    password_changed_at      timestamptz not null default now(),
    failed_attempts          integer not null default 0,
    locked_until             timestamptz,
    created_at               timestamptz not null default now(),
    updated_at               timestamptz not null default now(),

    constraint uq_local_credential_login_id
        unique (login_id_normalized),
    constraint ck_local_credential_login_id
        check (login_id ~ '^[A-Za-z0-9._-]{4,30}$'),
    constraint ck_local_credential_password_hash
        check (btrim(password_hash) <> ''),
    constraint ck_local_credential_failed_attempts
        check (failed_attempts >= 0)
);

create table email_verification_token (
    id                        uuid primary key,
    user_id                   uuid not null references app_user(id) on delete cascade,
    token_digest              varchar(64) not null,
    created_at                timestamptz not null default now(),
    expires_at                timestamptz not null,
    used_at                   timestamptz,

    constraint uq_email_verification_token_digest
        unique (token_digest),
    constraint ck_email_verification_token_digest
        check (token_digest ~ '^[0-9a-f]{64}$'),
    constraint ck_email_verification_token_expiry
        check (expires_at > created_at),
    constraint ck_email_verification_token_used
        check (used_at is null or used_at >= created_at)
);

create index ix_email_verification_token_user_active
    on email_verification_token(user_id, expires_at desc)
    where used_at is null;

create table password_reset_token (
    id                        uuid primary key,
    user_id                   uuid not null references app_user(id) on delete cascade,
    token_digest              varchar(64) not null,
    created_at                timestamptz not null default now(),
    expires_at                timestamptz not null,
    used_at                   timestamptz,

    constraint uq_password_reset_token_digest
        unique (token_digest),
    constraint ck_password_reset_token_digest
        check (token_digest ~ '^[0-9a-f]{64}$'),
    constraint ck_password_reset_token_expiry
        check (expires_at > created_at),
    constraint ck_password_reset_token_used
        check (used_at is null or used_at >= created_at)
);

create index ix_password_reset_token_user_active
    on password_reset_token(user_id, expires_at desc)
    where used_at is null;

create table spring_session (
    primary_id                char(36) not null,
    session_id                char(36) not null,
    creation_time             bigint not null,
    last_access_time          bigint not null,
    max_inactive_interval     integer not null,
    expiry_time               bigint not null,
    principal_name            varchar(100),

    constraint spring_session_pk primary key (primary_id)
);

create unique index spring_session_ix1
    on spring_session(session_id);

create index spring_session_ix2
    on spring_session(expiry_time);

create index spring_session_ix3
    on spring_session(principal_name);

create table spring_session_attributes (
    session_primary_id        char(36) not null,
    attribute_name            varchar(200) not null,
    attribute_bytes           bytea not null,

    constraint spring_session_attributes_pk
        primary key (session_primary_id, attribute_name),
    constraint spring_session_attributes_fk
        foreign key (session_primary_id)
        references spring_session(primary_id) on delete cascade
);

create table oauth_identity (
    id                        uuid primary key,
    user_id                   uuid not null
                              references app_user(id) on delete cascade,
    provider                  varchar(30) not null,
    provider_subject          varchar(255) not null,
    created_at                timestamptz not null default now(),
    last_login_at             timestamptz,

    constraint uq_oauth_identity_provider_subject
        unique (provider, provider_subject),
    constraint ck_oauth_identity_provider
        check (provider ~ '^[A-Z][A-Z0-9_]{1,29}$'),
    constraint ck_oauth_identity_subject
        check (btrim(provider_subject) <> '')
);

create index ix_oauth_identity_user
    on oauth_identity(user_id);

create table ledger_book (
    id                        uuid primary key,
    name                      varchar(100) not null,
    base_currency             char(3) not null default 'KRW',
    time_zone                 varchar(50) not null default 'Asia/Seoul',
    status                    varchar(20) not null default 'ACTIVE',
    created_by_user_id        uuid not null references app_user(id),
    created_at                timestamptz not null default now(),
    updated_at                timestamptz not null default now(),
    archived_at               timestamptz,
    version                   bigint not null default 0,

    constraint ck_ledger_book_name
        check (btrim(name) <> ''),
    constraint ck_ledger_book_currency
        check (base_currency = 'KRW'),
    constraint ck_ledger_book_status
        check (status in ('ACTIVE', 'ARCHIVED')),
    constraint ck_ledger_book_archived_at
        check ((status = 'ARCHIVED') = (archived_at is not null))
);

create table ledger_member (
    id                        uuid primary key,
    book_id                   uuid not null references ledger_book(id) on delete cascade,
    user_id                   uuid not null references app_user(id),
    joined_at                 timestamptz not null default now(),

    constraint uq_ledger_member_book_member
        unique (book_id, id),
    constraint uq_ledger_member_book_user_member
        unique (book_id, user_id, id),
    constraint uq_ledger_member_user
        unique (user_id)
);

create index ix_ledger_member_book
    on ledger_member(book_id, joined_at, id);

create table ledger_invitation (
    id                        uuid primary key,
    book_id                   uuid not null references ledger_book(id) on delete cascade,
    inviter_member_id         uuid not null,
    code_digest               varchar(64) not null,
    status                    varchar(20) not null default 'ACTIVE',
    created_at                timestamptz not null default now(),
    expires_at                timestamptz not null default (now() + interval '7 days'),
    redeemed_at               timestamptz,
    updated_at                timestamptz not null default now(),
    version                   bigint not null default 0,

    constraint fk_ledger_invitation_inviter
        foreign key (book_id, inviter_member_id)
        references ledger_member(book_id, id),
    constraint uq_ledger_invitation_book_id
        unique (book_id, id),
    constraint uq_ledger_invitation_code_digest
        unique (code_digest),
    constraint ck_ledger_invitation_code_digest
        check (code_digest ~ '^[0-9a-f]{64}$'),
    constraint ck_ledger_invitation_status
        check (status in ('ACTIVE', 'REDEEMED', 'REVOKED', 'EXPIRED')),
    constraint ck_ledger_invitation_expiry
        check (expires_at = created_at + interval '7 days'),
    constraint ck_ledger_invitation_redemption
        check ((status = 'REDEEMED') = (redeemed_at is not null))
);

create index ix_ledger_invitation_expiry_active
    on ledger_invitation(expires_at, id)
    where status = 'ACTIVE';

create table ledger_invitation_redemption (
    book_id                   uuid not null references ledger_book(id) on delete cascade,
    invitation_id             uuid not null references ledger_invitation(id) on delete cascade,
    user_id                   uuid not null references app_user(id),
    member_id                 uuid not null,
    redeemed_at               timestamptz not null default now(),

    constraint pk_ledger_invitation_redemption
        primary key (invitation_id),
    constraint uq_ledger_invitation_redemption_member
        unique (member_id),
    constraint fk_ledger_invitation_redemption_invitation
        foreign key (book_id, invitation_id)
        references ledger_invitation(book_id, id),
    constraint fk_ledger_invitation_redemption_member
        foreign key (book_id, user_id, member_id)
        references ledger_member(book_id, user_id, id)
);

create table asset_type (
    id                        uuid primary key,
    book_id                   uuid not null references ledger_book(id) on delete cascade,
    system_code               varchar(30),
    name                      varchar(100) not null,
    name_normalized           varchar(100)
                              generated always as (lower(name)) stored,
    behavior                  varchar(20) not null default 'STANDARD',
    payment_source_capable    boolean not null default false,
    is_custom                 boolean not null default true,
    sort_order                integer not null default 0,
    archived_at               timestamptz,
    created_by_member_id      uuid not null,
    created_at                timestamptz not null default now(),
    updated_at                timestamptz not null default now(),
    version                   bigint not null default 0,

    constraint uq_asset_type_book_id
        unique (book_id, id),
    constraint fk_asset_type_creator
        foreign key (book_id, created_by_member_id)
        references ledger_member(book_id, id),
    constraint ck_asset_type_name
        check (btrim(name) <> ''),
    constraint ck_asset_type_system_code
        check (system_code is null or system_code ~ '^[A-Z][A-Z0-9_]{1,29}$'),
    constraint ck_asset_type_behavior
        check (behavior in ('STANDARD', 'CREDIT_CARD')),
    constraint ck_asset_type_sort_order
        check (sort_order >= 0)
);

create unique index uq_asset_type_active_name
    on asset_type(book_id, name_normalized)
    where archived_at is null;

create unique index uq_asset_type_system_code
    on asset_type(book_id, system_code)
    where system_code is not null;

create index ix_asset_type_book_active
    on asset_type(book_id, sort_order, id)
    where archived_at is null;

create table asset (
    id                        uuid primary key,
    book_id                   uuid not null references ledger_book(id) on delete cascade,
    asset_type_id             uuid not null,
    ownership_scope           varchar(10) not null default 'PERSONAL',
    owner_member_id           uuid,
    name                      varchar(100) not null,
    name_normalized           varchar(100)
                              generated always as (lower(name)) stored,
    opened_on                 date not null,
    memo                      varchar(1000),
    include_in_net_worth      boolean not null default true,
    sort_order                integer not null default 0,
    archived_at               timestamptz,
    archived_by_member_id     uuid,
    created_by_member_id      uuid not null,
    updated_by_member_id      uuid not null,
    created_at                timestamptz not null default now(),
    updated_at                timestamptz not null default now(),
    version                   bigint not null default 0,

    constraint uq_asset_book_id
        unique (book_id, id),
    constraint fk_asset_type
        foreign key (book_id, asset_type_id)
        references asset_type(book_id, id),
    constraint fk_asset_owner
        foreign key (book_id, owner_member_id)
        references ledger_member(book_id, id),
    constraint fk_asset_creator
        foreign key (book_id, created_by_member_id)
        references ledger_member(book_id, id),
    constraint fk_asset_updater
        foreign key (book_id, updated_by_member_id)
        references ledger_member(book_id, id),
    constraint fk_asset_archiver
        foreign key (book_id, archived_by_member_id)
        references ledger_member(book_id, id),
    constraint ck_asset_name
        check (btrim(name) <> ''),
    constraint ck_asset_ownership
        check (
            (ownership_scope = 'PERSONAL' and owner_member_id is not null)
            or
            (ownership_scope = 'JOINT' and owner_member_id is null)
        ),
    constraint ck_asset_sort_order
        check (sort_order >= 0),
    constraint ck_asset_archive_actor
        check ((archived_at is null) = (archived_by_member_id is null))
);

create unique index uq_asset_active_name
    on asset(book_id, name_normalized)
    where archived_at is null;

create index ix_asset_book_active
    on asset(book_id, sort_order, id)
    where archived_at is null;

create index ix_asset_owner_active
    on asset(book_id, ownership_scope, owner_member_id, sort_order, id)
    where archived_at is null;

create table korean_public_holiday (
    holiday_on                date primary key,
    name                      varchar(100) not null,
    source                    varchar(50) not null default 'KASI_SPECIAL_DAY_API',
    fetched_at                timestamptz not null default now(),

    constraint ck_korean_public_holiday_name
        check (btrim(name) <> ''),
    constraint ck_korean_public_holiday_source
        check (btrim(source) <> '')
);

create table card_setting (
    card_asset_id                   uuid primary key,
    book_id                         uuid not null references ledger_book(id) on delete cascade,
    statement_closing_day           smallint not null,
    payment_day                     smallint not null,
    payment_month_offset            smallint not null default 1,
    settlement_asset_id             uuid,
    auto_settlement_enabled         boolean not null default false,
    created_at                      timestamptz not null default now(),
    updated_at                      timestamptz not null default now(),
    version                         bigint not null default 0,

    constraint fk_card_setting_card_asset
        foreign key (book_id, card_asset_id)
        references asset(book_id, id) on delete cascade,
    constraint fk_card_setting_settlement_asset
        foreign key (book_id, settlement_asset_id)
        references asset(book_id, id),
    constraint ck_card_setting_closing_day
        check (statement_closing_day between 1 and 31),
    constraint ck_card_setting_payment_day
        check (payment_day between 1 and 31),
    constraint ck_card_setting_payment_offset
        check (payment_month_offset between 0 and 2),
    constraint ck_card_setting_distinct_assets
        check (settlement_asset_id is null or settlement_asset_id <> card_asset_id),
    constraint ck_card_setting_auto_settlement
        check (
            not auto_settlement_enabled
            or settlement_asset_id is not null
        )
);

create index ix_card_setting_settlement_asset
    on card_setting(book_id, settlement_asset_id)
    where settlement_asset_id is not null;

create table category (
    id                        uuid primary key,
    book_id                   uuid not null references ledger_book(id) on delete cascade,
    kind                      varchar(10) not null,
    system_code               varchar(40),
    is_fallback               boolean not null default false,
    name                      varchar(100) not null,
    name_normalized           varchar(100)
                              generated always as (lower(name)) stored,
    icon_key                  varchar(50),
    color_token               varchar(50),
    sort_order                integer not null default 0,
    archived_at               timestamptz,
    created_by_member_id      uuid not null,
    updated_by_member_id      uuid not null,
    created_at                timestamptz not null default now(),
    updated_at                timestamptz not null default now(),
    version                   bigint not null default 0,

    constraint uq_category_book_id
        unique (book_id, id),
    constraint fk_category_creator
        foreign key (book_id, created_by_member_id)
        references ledger_member(book_id, id),
    constraint fk_category_updater
        foreign key (book_id, updated_by_member_id)
        references ledger_member(book_id, id),
    constraint ck_category_kind
        check (kind in ('INCOME', 'EXPENSE')),
    constraint ck_category_system_code
        check (system_code is null or system_code ~ '^[A-Z][A-Z0-9_]{1,39}$'),
    constraint ck_category_fallback
        check (not is_fallback or system_code = 'OTHER'),
    constraint ck_category_name
        check (btrim(name) <> ''),
    constraint ck_category_sort_order
        check (sort_order >= 0)
);

create unique index uq_category_active_name
    on category(book_id, kind, name_normalized)
    where archived_at is null;

create unique index uq_category_system_code
    on category(book_id, kind, system_code)
    where system_code is not null;

create unique index uq_category_fallback
    on category(book_id, kind)
    where is_fallback;

create index ix_category_book_active
    on category(book_id, kind, sort_order, id)
    where archived_at is null;

create table ledger_transaction (
    id                        uuid primary key,
    book_id                   uuid not null references ledger_book(id) on delete cascade,
    transaction_type          varchar(10) not null,
    transfer_subtype          varchar(30),
    occurred_on               date not null,
    amount_won                bigint not null,
    category_id               uuid,
    performed_by_member_id    uuid,
    description               varchar(500),
    source_type               varchar(30) not null default 'MANUAL',
    source_id                 uuid,
    created_by_member_id      uuid,
    updated_by_member_id      uuid,
    deleted_by_member_id      uuid,
    created_at                timestamptz not null default now(),
    updated_at                timestamptz not null default now(),
    deleted_at                timestamptz,
    version                   bigint not null default 0,

    constraint uq_ledger_transaction_book_id
        unique (book_id, id),
    constraint fk_ledger_transaction_category
        foreign key (book_id, category_id)
        references category(book_id, id),
    constraint fk_ledger_transaction_performer
        foreign key (book_id, performed_by_member_id)
        references ledger_member(book_id, id),
    constraint fk_ledger_transaction_creator
        foreign key (book_id, created_by_member_id)
        references ledger_member(book_id, id),
    constraint fk_ledger_transaction_updater
        foreign key (book_id, updated_by_member_id)
        references ledger_member(book_id, id),
    constraint fk_ledger_transaction_deleter
        foreign key (book_id, deleted_by_member_id)
        references ledger_member(book_id, id),
    constraint ck_ledger_transaction_type
        check (transaction_type in ('INCOME', 'EXPENSE', 'TRANSFER', 'ADJUSTMENT')),
    constraint ck_ledger_transaction_transfer_subtype
        check (
            (transaction_type = 'TRANSFER'
                and transfer_subtype in ('NORMAL', 'CARD_SETTLEMENT', 'CARD_PREPAYMENT'))
            or
            (transaction_type <> 'TRANSFER' and transfer_subtype is null)
        ),
    constraint ck_ledger_transaction_amount
        check (amount_won > 0),
    constraint ck_ledger_transaction_category
        check (
            (transaction_type in ('INCOME', 'EXPENSE') and category_id is not null)
            or
            (transaction_type in ('TRANSFER', 'ADJUSTMENT') and category_id is null)
        ),
    constraint ck_ledger_transaction_performer
        check (
            (transaction_type = 'ADJUSTMENT'
                and performed_by_member_id is null)
            or
            (transaction_type = 'TRANSFER'
                and transfer_subtype in ('CARD_SETTLEMENT', 'CARD_PREPAYMENT')
                and performed_by_member_id is null)
            or
            (transaction_type in ('INCOME', 'EXPENSE')
                and performed_by_member_id is not null)
            or
            (transaction_type = 'TRANSFER'
                and transfer_subtype = 'NORMAL'
                and performed_by_member_id is not null)
        ),
    constraint ck_ledger_transaction_source
        check (source_type in (
            'MANUAL',
            'IMPORT',
            'CARD_AUTOPAY',
            'CARD_PREPAYMENT',
            'OPENING_BALANCE',
            'SYSTEM'
        )),
    constraint ck_ledger_transaction_opening_balance
        check (
            (transaction_type = 'ADJUSTMENT'
                and source_type = 'OPENING_BALANCE'
                and source_id is not null)
            or
            (transaction_type <> 'ADJUSTMENT'
                and source_type <> 'OPENING_BALANCE')
        ),
    constraint ck_ledger_transaction_creator
        check (
            source_type in ('CARD_AUTOPAY', 'SYSTEM')
            or created_by_member_id is not null
        ),
    constraint ck_ledger_transaction_delete_actor
        check ((deleted_at is null) = (deleted_by_member_id is null))
);

create unique index uq_ledger_transaction_source
    on ledger_transaction(book_id, source_type, source_id)
    where source_id is not null;

create index ix_ledger_transaction_daily
    on ledger_transaction(book_id, occurred_on desc, created_at desc, id desc)
    where deleted_at is null;

create index ix_ledger_transaction_expense_stats
    on ledger_transaction(book_id, occurred_on, category_id, performed_by_member_id)
    where transaction_type = 'EXPENSE' and deleted_at is null;

create index ix_ledger_transaction_income_stats
    on ledger_transaction(book_id, occurred_on, category_id, performed_by_member_id)
    where transaction_type = 'INCOME' and deleted_at is null;

create table transaction_posting (
    transaction_id            uuid not null,
    line_no                   smallint not null,
    book_id                   uuid not null references ledger_book(id) on delete cascade,
    asset_id                  uuid not null,
    delta_won                 bigint not null,

    constraint pk_transaction_posting
        primary key (transaction_id, line_no),
    constraint fk_transaction_posting_transaction
        foreign key (book_id, transaction_id)
        references ledger_transaction(book_id, id) on delete cascade,
    constraint fk_transaction_posting_asset
        foreign key (book_id, asset_id)
        references asset(book_id, id),
    constraint uq_transaction_posting_asset
        unique (transaction_id, asset_id),
    constraint ck_transaction_posting_line_no
        check (line_no > 0),
    constraint ck_transaction_posting_delta
        check (delta_won <> 0)
);

create index ix_transaction_posting_asset_balance
    on transaction_posting(book_id, asset_id, transaction_id)
    include (delta_won);

create table card_statement (
    id                        uuid primary key,
    book_id                   uuid not null references ledger_book(id) on delete cascade,
    card_asset_id             uuid not null,
    cycle_start               date not null,
    cycle_end                 date not null,
    due_on                    date not null,
    status                    varchar(20) not null default 'OPEN',
    billed_amount_won         bigint not null default 0,
    finalized_at              timestamptz,
    settled_at                timestamptz,
    created_at                timestamptz not null default now(),
    updated_at                timestamptz not null default now(),
    version                   bigint not null default 0,

    constraint uq_card_statement_book_id
        unique (book_id, id),
    constraint fk_card_statement_card_asset
        foreign key (book_id, card_asset_id)
        references asset(book_id, id),
    constraint uq_card_statement_cycle
        unique (card_asset_id, cycle_start, cycle_end),
    constraint ck_card_statement_dates
        check (cycle_start <= cycle_end and cycle_end <= due_on),
    constraint ck_card_statement_status
        check (status in ('OPEN', 'FINALIZED', 'PAID', 'CANCELLED')),
    constraint ck_card_statement_amount
        check (billed_amount_won >= 0),
    constraint ck_card_statement_finalized_at
        check (
            (status = 'OPEN' and finalized_at is null and settled_at is null)
            or
            (status in ('FINALIZED', 'CANCELLED')
                and finalized_at is not null and settled_at is null)
            or
            (status = 'PAID' and finalized_at is not null and settled_at is not null)
        )
);

create index ix_card_statement_card_status_due
    on card_statement(card_asset_id, status, due_on, id);

create table card_charge (
    id                        uuid primary key,
    book_id                   uuid not null references ledger_book(id) on delete cascade,
    source_transaction_id     uuid not null,
    card_asset_id             uuid not null,
    statement_id              uuid not null,
    charge_origin             varchar(20) not null default 'PURCHASE',
    installment_no            smallint not null default 1,
    installment_count         smallint not null default 1,
    principal_amount_won      bigint not null,
    expected_settlement_on    date not null,
    created_at                timestamptz not null default now(),

    constraint uq_card_charge_book_id
        unique (book_id, id),
    constraint fk_card_charge_transaction
        foreign key (book_id, source_transaction_id)
        references ledger_transaction(book_id, id),
    constraint fk_card_charge_card_asset
        foreign key (book_id, card_asset_id)
        references asset(book_id, id),
    constraint fk_card_charge_statement
        foreign key (book_id, statement_id)
        references card_statement(book_id, id) on delete cascade,
    constraint uq_card_charge_installment
        unique (source_transaction_id, installment_no),
    constraint ck_card_charge_origin
        check (charge_origin in ('PURCHASE', 'OPENING_BALANCE')),
    constraint ck_card_charge_installment
        check (
            installment_count > 0
            and installment_no between 1 and installment_count
        ),
    constraint ck_card_charge_principal
        check (principal_amount_won > 0)
);

create index ix_card_charge_statement
    on card_charge(statement_id, id);

create index ix_card_charge_forecast
    on card_charge(book_id, card_asset_id, expected_settlement_on);

create table card_payment_schedule (
    id                              uuid primary key,
    book_id                         uuid not null references ledger_book(id) on delete cascade,
    statement_id                    uuid not null unique,
    settlement_asset_id             uuid not null,
    scheduled_on                    date not null,
    status                          varchar(20) not null default 'SCHEDULED',
    attempt_count                   integer not null default 0,
    last_error                      varchar(500),
    next_retry_at                   timestamptz,
    created_at                      timestamptz not null default now(),
    updated_at                      timestamptz not null default now(),
    version                         bigint not null default 0,

    constraint fk_card_payment_schedule_statement
        foreign key (book_id, statement_id)
        references card_statement(book_id, id) on delete cascade,
    constraint fk_card_payment_schedule_asset
        foreign key (book_id, settlement_asset_id)
        references asset(book_id, id),
    constraint ck_card_payment_schedule_status
        check (status in ('SCHEDULED', 'PROCESSING', 'COMPLETED', 'FAILED', 'CANCELLED')),
    constraint ck_card_payment_schedule_attempts
        check (attempt_count >= 0)
);

create index ix_card_payment_schedule_due
    on card_payment_schedule(scheduled_on, id)
    where status in ('SCHEDULED', 'FAILED');

create table card_statement_payment (
    id                              uuid primary key,
    book_id                         uuid not null references ledger_book(id) on delete cascade,
    statement_id                    uuid not null,
    payment_type                    varchar(20) not null,
    settlement_asset_id             uuid not null,
    amount_won                      bigint not null,
    paid_on                         date not null,
    settlement_transaction_id       uuid not null unique,
    created_by_member_id            uuid,
    created_at                      timestamptz not null default now(),

    constraint uq_card_statement_payment_book_id
        unique (book_id, id),
    constraint fk_card_statement_payment_statement
        foreign key (book_id, statement_id)
        references card_statement(book_id, id) on delete cascade,
    constraint fk_card_statement_payment_asset
        foreign key (book_id, settlement_asset_id)
        references asset(book_id, id),
    constraint fk_card_statement_payment_transaction
        foreign key (book_id, settlement_transaction_id)
        references ledger_transaction(book_id, id),
    constraint fk_card_statement_payment_creator
        foreign key (book_id, created_by_member_id)
        references ledger_member(book_id, id),
    constraint ck_card_statement_payment_type
        check (payment_type in ('PREPAYMENT', 'REGULAR')),
    constraint ck_card_statement_payment_amount
        check (amount_won > 0),
    constraint ck_card_statement_payment_creator
        check (
            (payment_type = 'PREPAYMENT' and created_by_member_id is not null)
            or
            (payment_type = 'REGULAR')
        )
);

create unique index uq_card_statement_regular_payment
    on card_statement_payment(statement_id)
    where payment_type = 'REGULAR';

create index ix_card_statement_payment_statement
    on card_statement_payment(statement_id, paid_on, id);

create table api_idempotency (
    id                        uuid primary key,
    actor_user_id             uuid not null references app_user(id),
    book_id                   uuid references ledger_book(id) on delete cascade,
    endpoint_scope            varchar(100) not null,
    idempotency_key           varchar(100) not null,
    request_hash              varchar(64) not null,
    processing_status         varchar(20) not null default 'IN_PROGRESS',
    response_status           integer,
    resource_id               uuid,
    response_body             jsonb,
    created_at                timestamptz not null default now(),
    completed_at              timestamptz,
    expires_at                timestamptz not null,

    constraint uq_api_idempotency_actor_scope_key
        unique (actor_user_id, endpoint_scope, idempotency_key),
    constraint ck_api_idempotency_status
        check (processing_status in ('IN_PROGRESS', 'COMPLETED', 'FAILED')),
    constraint ck_api_idempotency_expiry
        check (expires_at > created_at),
    constraint ck_api_idempotency_completion
        check (
            (processing_status = 'IN_PROGRESS' and completed_at is null)
            or
            (processing_status in ('COMPLETED', 'FAILED') and completed_at is not null)
        )
);

create index ix_api_idempotency_expiry
    on api_idempotency(expires_at);

create table audit_log (
    sequence                  bigint generated always as identity primary key,
    book_id                   uuid references ledger_book(id) on delete cascade,
    actor_type                varchar(10) not null,
    actor_member_id           uuid references ledger_member(id),
    entity_type               varchar(40) not null,
    entity_id                 uuid not null,
    action                    varchar(40) not null,
    entity_version            bigint,
    before_data               jsonb,
    after_data                jsonb,
    request_id                uuid,
    occurred_at               timestamptz not null default now(),

    constraint ck_audit_log_actor
        check (
            (actor_type = 'USER' and actor_member_id is not null)
            or
            (actor_type = 'SYSTEM' and actor_member_id is null)
        )
);

create index ix_audit_log_entity
    on audit_log(entity_type, entity_id, occurred_at desc);

create index ix_audit_log_book_time
    on audit_log(book_id, occurred_at desc)
    where book_id is not null;

create view asset_current_balance as
select
    asset.id as asset_id,
    asset.book_id,
    coalesce(
        sum(transaction_posting.delta_won)
            filter (where ledger_transaction.deleted_at is null),
        0
    ) as current_balance_won
from asset
left join transaction_posting
       on transaction_posting.book_id = asset.book_id
      and transaction_posting.asset_id = asset.id
left join ledger_transaction
       on ledger_transaction.book_id = transaction_posting.book_id
      and ledger_transaction.id = transaction_posting.transaction_id
group by asset.id, asset.book_id;

create view card_statement_forecast as
with charge_totals as (
    select
        card_charge.statement_id,
        coalesce(
            sum(card_charge.principal_amount_won)
                filter (where ledger_transaction.deleted_at is null),
            0
        ) as charge_amount_won
    from card_charge
    join ledger_transaction
      on ledger_transaction.book_id = card_charge.book_id
     and ledger_transaction.id = card_charge.source_transaction_id
    group by card_charge.statement_id
), payment_totals as (
    select
        card_statement_payment.statement_id,
        coalesce(
            sum(card_statement_payment.amount_won)
                filter (where ledger_transaction.deleted_at is null),
            0
        ) as paid_amount_won
    from card_statement_payment
    join ledger_transaction
      on ledger_transaction.book_id = card_statement_payment.book_id
     and ledger_transaction.id = card_statement_payment.settlement_transaction_id
    group by card_statement_payment.statement_id
), statement_amounts as (
    select
        card_statement.id as statement_id,
        case
            when card_statement.status = 'OPEN' then
                coalesce(charge_totals.charge_amount_won, 0)
            when card_statement.status in ('FINALIZED', 'PAID') then
                card_statement.billed_amount_won
            else 0
        end as gross_amount_won,
        coalesce(payment_totals.paid_amount_won, 0) as paid_amount_won
    from card_statement
    left join charge_totals
      on charge_totals.statement_id = card_statement.id
    left join payment_totals
      on payment_totals.statement_id = card_statement.id
)
select
    card_statement.id as statement_id,
    card_statement.book_id,
    card_statement.card_asset_id,
    card_statement.due_on,
    card_statement.status,
    statement_amounts.gross_amount_won,
    statement_amounts.paid_amount_won,
    greatest(
        statement_amounts.gross_amount_won - statement_amounts.paid_amount_won,
        0
    ) as payment_amount_won
from card_statement
join statement_amounts
  on statement_amounts.statement_id = card_statement.id;
